### ISSUE TITLE
change theme to Neve

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/domainwheel-theme#18]
The current theme doesn't support a decent footer, dropdowns, articles are awful to read ( https://domainwheel.com/how-to-start-a-blog/ ) and homepage is built using elementor.

My idea is to change it to Neve and integrate with the reactapp, instead of Elementor use plain php/html, get rid of jquery and make sure the mobile loading is as fast as possible since 50% of users here are visiting on mobile

@selul @abaicus maybe once you guys get some time you can investigate if my idea is feasible and write down some guildes so @cosmin-serbanescu can work on it. If there is nothing out of the ordinary going on, cosmin then work on it direcly.

cc @sab2ina

**Comment by ineagu** [comment]
@sab2ina we can work on this probably after RS

**Comment by cosmin-serbanescu** [comment]
enhancements from yesterday's meeting:

- have a way of placing the domainwheel plugin on TI/CW:  probably the best way is by having a settings page https://github.com/Codeinwp/domainwheel/issues/79
- have AMP on homepage and see what we can do with that search (?) OR have the search results in a separate page
